### PR TITLE
convert/new: add support for outputting cascading selects.

### PR DESCRIPTION
**Pull request by issa-tseng**
* see opendatakit/build#162 for details.

### CODE REVIEW

**Comment by issa-tseng** [comment]
This still needs a ✅ !

**Comment by issa-tseng** [comment]
Out of time. Merging this.

**Comment by lognaturel** [comment]
Thank you, sorry, I forgot to come back to these!!

**Comment by issa-tseng** [comment]
At least this project has comprehensive tests!

**Pull request merged**
